### PR TITLE
feat: use githack instead of githubusercontent

### PR DESCRIPTION
**Pull request by matfax**
This feature let's this action use [githack](https://raw.githack.com/) instead of `githubusercontent`.
Moreover, I've added a `cdn` input that allows switching to the githack CDN channel.

### CODE REVIEW

**Comment by prototypicalpro** [comment]
This looks good, however for modularity's sake I will go ahead and refactor the `cdn` input into a string domain so someone can specify any CDN (including githack). Out of curiosity, what are the benefits to using githack in this case?

**Comment by prototypicalpro** [comment]
Would this work for you: https://github.com/prototypicalpro/compile-badges-action/compare/feat/custom-cdn?

**Comment by matfax** [comment]
@prototypicalpro The advantage of using githack is that it adds a content header and optionally, CloudFlare's optimizations as well, of course (e.g., compression). The missing content header from GitHub makes it difficult for specific file types and firewalls or clients to be accepted or rendered correctly. HTML from githubusercontents, for example, is rendered as text by Chrome. I guess GitHub doesn't want their repositories to be used as a web host.

Your `custom-cdn` looks fine by me.

**Comment by prototypicalpro** [comment]
Alright, those changes are up on version [v1.1.0](https://github.com/prototypicalpro/compile-badges-action/releases/tag/v1.1.0). Thanks!

**Pull request closed without merging**
